version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./uploads:/app/uploads
    environment:
      - ENVIRONMENT=development
      - DEBUG=true
    restart: unless-stopped
    
  # Optional: Add a database service for future migration
  # db:
  #   image: postgres:13
  #   environment:
  #     POSTGRES_DB: fineprint_simplifier
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: password
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"

# volumes:
#   postgres_data:
